config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :articles
    #same as the one below is just short cut
    # resources :articles, only:[:show, :index, :new, :create, :edit, :update, :destroy]
root 'pages#home'
get 'about', to: 'pages#about'
get 'signup', to: 'users#new'
resources :users, except: [:new]
get 'login' , to: 'sessions#new' #to get the data from database
post 'login' , to: 'sessions#create' #to post the form request
delete 'logout', to: 'sessions#destroy'
resources :categories ,except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
    class Article < ApplicationRecord
      belongs_to :user
      has_many :article_categories
      has_many :categories, through: :article_categories
      validates :title, presence:true, length:{minimum: 6, maximum:100}
      validates :description,presence:true, length:{minimum:10, maximum:500}
    end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to  :article
  belongs_to  :category
end

app/models/category.rb
class Category < ApplicationRecord
 validates :name, presence: true, length:{minimum:3, maximum: 25}
 validates_uniqueness_of :name
 has_many :article_categories
 has_many :articles, through: :article_categories
end

app/models/user.rb
 class User < ApplicationRecord
   before_save {self.email = email.downcase }
    has_many :articles, dependent: :destroy
    validates :username, presence: true,
              uniqueness: { case_sensitive: false },
              length: { minimum: 3, maximum:25 }
     VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
     validates :email, presence: true,
               uniqueness: { case_sensitive: false },
               length: { maximum:105 },
               format: {with:VALID_EMAIL_REGEX}
   has_secure_password
 end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user , :logged_in?
  #to make available on  views and controller
  def current_user
   @current_user ||= User.find(session[:user_id]) if session[:user_id]
 #if current_user exist or equil to this user then keep going
    end

    def logged_in?
      !!current_user
      #to check if current_user is access, yes or no
    end

    def require_user
      if !logged_in?
        flash[:alert] = "Yoou must be logged in to perform that action"
        redirect_to login_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :set_article, only:[:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show , :index]
  before_action :require_same_user, only:[:edit, :update, :destroy]
  def show
  end
  def index
    @articlesIndex =Article.paginate(page: params[:page], per_page: 3)
  end
  def new
   @article = Article.new
  end
  def edit
  end
  def create
    @article = Article.new(aritcles_perams)
    @article.user = current_user
    if @article.save
      flash[:notice]= "Article was created successfully."
    redirect_to @article
  else
    render "new"
  end
  end
  def update
   if @article.update(aritcles_perams)
     flash[:notice] = "artice has been updated"
       redirect_to @article
   else
     render "edit"

   end
 end
 def destroy
 @article.destroy

 redirect_to articles_path
 end
 private  #mean it's only allowed in this contrller only

  def set_article
   @article = Article.find(params[:id])
 end

 def aritcles_perams
   params.require(:article).permit(:title, :description, category_ids: [])
 end
 def require_same_user
   if current_user != @article.user && !current_user.admin?
     flash[:alert] = "You can only edit or delete yoour own article"
     redirect_to @article
   end
end


end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]
 def new
  @category = Category.new
 end
 def create
   @category = Category.new(category_params)
   if @category.save
     flash[:notice] = "category was successfuly created"
     redirect_to @category
   else
     render "new"
   end
 end
 def edit
   @category = Category.find(params[:id])
 end
 def update
   @category = Category.find(params[:id])
   if @category.update(category_params)
     flash[:notice] = "category has been updated"
     redirect_to @category
   else
     render 'edit'
   end
 end
 def index

 @categories = Category.paginate(page: params[:page], per_page: 3)
 end
 def show
  @category = Category.find(params[:id])
  @articlesIndex = @category.articles.paginate(page: params[:page], per_page: 3)
 end
  private
  def category_params
    params.require(:category).permit(:name)
  end
  def require_admin
    if !(logged_in? && current_user.admin?)
      flash[:alert] = "only admin can perform that action"
      redirect_to categories_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  end
  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)#to check if the email iss exist on the databasse table
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "logged in succcessfully"
      redirect_to user
    else
      flash.now[:alert] = "there wass somthing wrong with your database"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "logged out"
    redirect_to  articles_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user ,only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:edit , :update]
  before_action :require_same_user ,only: [:edit, :update ,:destroy]

  def show
      @articlesIndex = @user.articles.paginate(page: params[:page], per_page: 3)
      # to show articles that related to user based in user id
    end
    def index
      @user = User.paginate(page: params[:page], per_page: 3)
    end
  def new
    @user = User.new
  end
  def edit

  end
  def update

   if @user.update(user_perams)
     flash[:notice] = "Your account has been updated successfuly #{@user.username}"
     redirect_to @user
  else
    render 'edit'
  end
  end
  def create
    @user = User.new(user_perams)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome to  #{@user.username},you have successfuly signed up"
      redirect_to articles_path

  else
    render 'new'
  end
  end
  def destroy
  @user.destroy
  session[:user_id] = nil if @user == current_user
  flash[:notice] = "Account and all associated articles successfully deleted"
  redirect_to articles_path
  end
  private
  def user_perams
    params.require(:user).permit(:username, :email, :password)
  end
  def set_user
    @user = User.find(params[:id])
  end
  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own profile"
      redirect_to @user
    end
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80})
  email_address = user.email.downcase
  hash = Digest::MD5.hexdigest(email_address)
  size = options[:size]
  gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
  image_tag(gravatar_url, alt: user.username, class: "rounded shadow mx-auto d-block")
end



end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<table>
  <thead>
    <tr>
      <th>author</th>
      <th>title</th>
      <th>description</th>
      <th colspan="3">action</th>
    </tr>
  </thead>

  <tbody>
    <% @articlesIndex.each do |article| %>
    <tr>
      <% if article.user %>
        <td>by <%= link_to article.user.username, user_path(article.user) %></td>
       <% end %>
      <td><%= article.title %></td>
      <td><%= article.description %></td>
      <% if article.categories.any? %>
      <td><%= render article.categories %></td>
      <% end %>
      <td><%= link_to'show', article_path(article.id)%></td>
      <% if logged_in? && (article.user == current_user || current_user.admin ) %>
      <td><%= link_to'edit',  edit_article_path(article.id)%></td>
      <td><%= link_to'Delete', article_path(article.id), method: :Delete , data: { confirm:"are you sure?" }%></td>
      <% end %>
    </tr>

    <% end %>

  </tbody>
</table>
<br>
<% if logged_in? %>
<%= link_to 'create new artice',new_article_path %>
<% end %>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj:@article %>
<%= form_with(model: @article, local: true) do |f| %>
<p>
<%= f.label :title %><br/>
<%= f.text_field :title %>
</p>

<p>
<%= f.label :description %><br/>
<%= f.text_area :description %>
</p>
<%= f.label :category %><br/>
 <%= f.collection_select(:category_ids, Category.all, :id, :name,
     {promt: "choose a category (can be empty)"},{multiple: true,size:3, class: "custome-select" }) %>

<p>
<%= f.submit %>
</p>
<% end %>

app/views/articles/edit.html.erb
<h1>Edite Article</h1>
<br>
<%= render 'form' %>

app/views/articles/index.html.erb
<h1>Articles Listing page</h1>
<% if logged_in? %>
<a><%= link_to "logout", logout_path, method: :delete %></a>
<a><%= link_to current_user.username, user_path(current_user) %></a>
<%= "(admin)" if current_user.admin? %> <a><%= link_to "user profile" ,user_path(current_user) %></a>
<a><%= link_to "edit your profile" ,edit_user_path(current_user) %></a>
<a><%= link_to "Delete your profile" ,user_path(current_user), method: :delete, data: { confirm: "Are you sure?" } %></a>
<% else %>
<a><%= link_to "login", login_path %></a>
<a><%= link_to "sign up", signup_path %></a>
<% end %>
<% if logged_in? && current_user.admin? %>
<a><%= link_to " create new category" ,new_category_path %></a>
<% end %>
<a><%= link_to "categories" ,categories_path %></a>
<br><br><br>
<%= render 'article' %>

<div class="apple_pagination">
    <%= will_paginate  @articlesIndex, :container => false %>
  </div>

app/views/articles/new.html.erb
<h1>New Article</h1>
<br>
<%= render 'form' %>
<%= link_to "Home page",articles_path %>

app/views/articles/show.html.erb
<h1>Articles</h1>
<p><strong>Title:</strong> <%= @article.title %></p>
<p><strong>Description:</strong><%= @article.description %></p>
<p><strong>auther:</strong><%= @article.user.username %></p>
<%= link_to gravatar_for(@article.user), user_path(@article.user) %>|
<% if @article.categories.any? %>
<p><%= render @article.categories %></p>
<% end %>
<% if logged_in? && (@article.user == current_user || current_user.admin) %>
<%= link_to 'edit',  edit_article_path(@article)%>|
<%= link_to 'Delete', article_path(@article), method: :Delete, data: { confirm:"are you sure?" } %>|
<% end %>
<%= link_to 'Home page', articles_path%>

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category) %> |

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj:@category %>
<%= form_with(model: @category, local: true) do |f| %>
<p>
<%= f.label :name,"Category name" %><br/>
<%= f.text_field :name %>
</p>

<p>
<%= f.submit %>
</p>
<% end %>

app/views/categories/edit.html.erb
<h1 class="text-center mt-4">edit category</h1>
<%= render "form" %>

app/views/categories/index.html.erb
<h1 class="text-center mt-4">categories</h1>
<table>
  <tbody>
    <% @categories.each do |category| %>
    <tr>

      <td><%= link_to category.name ,category_path(category)%></td>
      <td><%= pluralize(category.articles.count , "article") %></td>
    </tr>

    <% end %>

  </tbody>
</table>
<br>
<div class="apple_pagination">
    <%= will_paginate  @categories, :container => false %>
  </div>

app/views/categories/new.html.erb
<h1 class="text-center mt-4">create a new category</h1>
<%= render "form" %>

app/views/categories/show.html.erb
<h1 class="text-center mt-4">Category: <%= @category.name %></h1>
<% if logged_in? && current_user.admin %>
<h1 class="text-center mt-4"><%= link_to "edit category name", edit_category_path(@category) %></h1>
<% end %>

<h1 class="text-center mt-4">Articles</h1>

<%=  render 'articles/article'  %>

<div class="apple_pagination">
    <%= will_paginate  @articlesIndex, :container => false %>
  </div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, batis| %>
<%= batis  %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Welcome to home page</h1>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<h2 class="alert">The following errors prevented the <%= obj.class.name.downcase %> from beign saved</h2>
<ul>
<% obj.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj:@user %>
<%= form_with(model: @user, local: true) do |f| %>
<p>
<%= f.label :username %><br/>
<%= f.text_field :username %>
</p>

<p>
<%= f.label :email %><br/>
<%= f.email_field :email %>
</p>
<p>
<%= f.label :password %><br/>
<%= f.password_field :password %>
</p>

<p>
<%= f.submit(@user.new_record? ? "Sign Up" : "update account" ) %>
</p>
<% end %>

app/views/users/edit.html.erb
<h1 class="text-center mt-4">edit your profile</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<h1 class="text-center mt-4">Alpha Blogers</h1>

  <table>
    <thead>
      <tr>
        <th>author</th>
        <th>Profile image</th>
        <th>Number of articles</th>
        <th colspan="2">action</th>
        <th>joiend at</th>
      </tr>
    </thead>

    <tbody>
      <% @user.each do |user| %>
      <tr>
         <td>by <%= link_to user.username, user_path(user) %></td>
        <td><%= link_to gravatar_for(user, size: 150), user_path(user) %></td>
        <td><%= pluralize(user.articles.count , "article") %></td>
        <td><%= link_to'view profile', user_path(user) %></td>
      <% if logged_in?%>
         <% if user == current_user %>
        <td><%= link_to'edit',  edit_user_path(user.id)%></td>
         <% end %>
        <% if current_user.admin? %>
     <td><%= link_to 'delete user', user_path(user.id), method: :delete, data: {confirm:"aree you sure want to delete user and all the accosiated blogs"}%></td>
          <% end %>
      <% end %>
        <td> <%= time_ago_in_words(user.created_at) %></td>
      </tr>

      <% end %>

    </tbody>
  </table>
  <div class="apple_pagination">
    <%= will_paginate  @user, :container => false %>
  </div>
  <br>

app/views/users/new.html.erb
<h1 class="text-center mt-4">Sign up for Alpha Blog</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h1 class="text-center mt-4"><%= @user.username %>'s profile</h1>
<a><%= link_to "logout", logout_path, method: :delete %></a>

<%= gravatar_for @user, size: 200 %>
<% if logged_in? && @user == current_user %>
<h1 class="text-center mt-4"><%= link_to "edit your profile", edit_user_path(@user) %></h1>
<% end %>

<h1 class="text-center mt-4">Articles</h1>

<%=  render 'articles/article'  %>

<div class="apple_pagination">
    <%= will_paginate  @articlesIndex, :container => false %>
  </div>